name: iOS Test Runner

on: [pull_request]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: latest-stable
      - name: Test
        run: |
          xcodebuild \
            -scheme SquarePointOfSaleSDK \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
            test
